In [1]:
import os, time, requests
import pandas as pd
from sqlalchemy import create_engine, text
from dotenv import load_dotenv

load_dotenv()
engine = create_engine(
    f"mysql+pymysql://{os.getenv('DB_USER')}:{os.getenv('DB_PASSWORD')}"
    f"@{os.getenv('DB_HOST')}:{os.getenv('DB_PORT')}/{os.getenv('DB_NAME')}?charset=utf8mb4"
)

cities = {
    "Amsterdam": {"lat": 52.3676, "lon": 4.9041,  "country": "NLD"},
    "Barcelona": {"lat": 41.3874, "lon": 2.1686,  "country": "ESP"},
    "Berlin":    {"lat": 52.5200, "lon": 13.4050, "country": "DEU"},
    "Columbus":  {"lat": 39.9612, "lon": -82.9988, "country": "USA"},
}

In [2]:
HEADERS = {"User-Agent": "airbnb-student-project/1.0 (contact:rofaidaesmail234@gmail.com)"}
URL = "https://en.wikipedia.org/w/api.php"

rows = []
for city, c in cities.items():
    params = {
        "action": "query", "list": "geosearch", "format": "json",
        "gscoord": f"{c['lat']}|{c['lon']}", "gsradius": 10000, "gslimit": 500,
    }
    r = requests.get(URL, params=params, headers=HEADERS, timeout=30)
    r.raise_for_status()
    for p in r.json()["query"]["geosearch"]:
        rows.append({
            "city": city, "name": p["title"],
            "latitude": p["lat"], "longitude": p["lon"],
            "distance_from_center_m": p["dist"],
            "source_url": f"https://en.wikipedia.org/?curid={p['pageid']}",
        })
    time.sleep(1)

landmarks = pd.DataFrame(rows)
print(landmarks.groupby("city").size())
landmarks.head()

city
Amsterdam    500
Barcelona    500
Berlin       500
Columbus     500
dtype: int64

,city,name,latitude,longitude,distance_from_center_m,source_url
0,Amsterdam,Joods Historisch Museum,52.366944,4.904028,73.1,https://en.wikipedia.org/?curid=9088510
1,Amsterdam,Mozes en Aäronkerk,52.368056,4.903056,87.1,https://en.wikipedia.org/?curid=41470849
2,Amsterdam,Portuguese Synagogue (Amsterdam),52.367500,4.905400,89.0,https://en.wikipedia.org/?curid=8095914
3,Amsterdam,Netherlands Film Academy,52.368333,4.904722,91.8,https://en.wikipedia.org/?curid=575829
4,Amsterdam,Leprozengracht,52.367340,4.902323,124.1,https://en.wikipedia.org/?curid=61385298

In [3]:
landmarks.groupby("city").head(15)[["city", "name", "distance_from_center_m"]]

,city,name,distance_from_center_m
0,Amsterdam,Joods Historisch Museum,73.1
1,Amsterdam,Mozes en Aäronkerk,87.1
2,Amsterdam,Portuguese Synagogue (Amsterdam),89.0
3,Amsterdam,Netherlands Film Academy,91.8
4,Amsterdam,Leprozengracht,124.1
5,Amsterdam,Markenplein,137.8
6,Amsterdam,Nieuwe Herengracht,168.8
7,Amsterdam,Waterlooplein metro station,170.5
8,Amsterdam,Stopera,170.5
9,Amsterdam,Houtgracht,172.8
10,Amsterdam,290 Square Meters,181.1
11,Amsterdam,Waterlooplein,184.2
12,Amsterdam,Reinwardt Academie,185.9
13,Amsterdam,Jodenbreestraat,188.1
14,Amsterdam,Maupoleum,202.8
500,Barcelona,Bombing of Barcelona,125.0
501,Barcelona,Barcelona Metro line 1,125.0
502,Barcelona,Plaça de Catalunya station,127.3
503,Barcelona,"Carrer de Bergara, Barcelona",137.5
504,Barcelona,Plaça de Catalunya,142.4
505,Barcelona,"Ronda de la Universitat, Barcelona",161.8
506,Barcelona,"Carrer de Pelai, Barcelona",173.2
507,Barcelona,Avinguda de la Llum,175.6
508,Barcelona,"Consulate General of the Philippines, Barcelona",213.6
509,Barcelona,Coliseum (Barcelona),220.1
510,Barcelona,Gran Via de les Corts Catalanes,267.0
511,Barcelona,Font de Canaletes,268.6
512,Barcelona,Santa Anna de Barcelona,287.0
513,Barcelona,Portal de l'Àngel,290.7
514,Barcelona,Passeig de Gràcia station,297.1
1000,Berlin,2010 Air Service Berlin Douglas C-47 crash,0.0
1001,Berlin,Marmorhaus,0.0
1002,Berlin,Berlin,0.0
1003,Berlin,Old Synagogue (Berlin),123.1
1004,Berlin,"St. Mary's Church, Berlin",128.6
1005,Berlin,Mitte (locality),128.6
1006,Berlin,Neptune Fountain (Berlin),134.1
1007,Berlin,AquaDom,153.5
1008,Berlin,East Berlin,158.9
1009,Berlin,Berlin Dungeon,187.5
1010,Berlin,Marx-Engels Forum,193.7
1011,Berlin,Rosenstrasse protest,204.3
1012,Berlin,Karl-Liebknecht-Straße,215.5
1013,Berlin,DDR Museum,216.8
1014,Berlin,Rotes Rathaus (Berlin U-Bahn),240.9
1500,Columbus,Ohio Statehouse,22.3
1501,Columbus,Capitol Square,32.5
1502,Columbus,Ohio General Assembly,45.3
1503,Columbus,The Spirit of '98,63.7
1504,Columbus,Ohio Veterans Plaza,64.7
1505,Columbus,The Doughboy (Ivone),78.1
1506,Columbus,Statue of Christopher Columbus (Ohio Statehouse),79.9
1507,Columbus,Ohio Holocaust and Liberators Memorial,95.2
1508,Columbus,These Are My Jewels,103.5
1509,Columbus,Peace (Saville),107.5
1510,Columbus,William McKinley Monument,115.1
1511,Columbus,Naiads (Greaves),121.6
1512,Columbus,Hartman Building and Theater,130.4
1513,Columbus,Columbus City Hall (1872–1921),131.2
1514,Columbus,Columbus Dispatch Building,136.1

In [4]:
exclude = [
    "station", "metro", "line ", "street", "straße", "strasse", "carrer", "gracht",
    "avenue", "avinguda", "road", "crash", "bombing", "protest", "consulate",
    "embassy", "academy", "university", "school", "district", "locality",
    "(locality)", "east berlin", "west berlin", "list of", "history of",
]
pattern_ex = "|".join(exclude)

mask = ~landmarks["name"].str.lower().str.contains(pattern_ex, na=False)
mask &= landmarks["name"].str.lower() != landmarks["city"].str.lower()   # شيلي صفحة المدينة نفسها
clean_lm = landmarks[mask].copy()
print(clean_lm.groupby("city").size())
clean_lm.groupby("city").head(15)[["city", "name", "distance_from_center_m"]]

city
Amsterdam    421
Barcelona    380
Berlin       428
Columbus     411
dtype: int64

C:\Users\rokas\AppData\Local\Temp\ipykernel_23980\3943134667.py:9: UserWarning: This pattern is interpreted as a regular expression, and has match groups. To actually get the groups, use str.extract.
  mask = ~landmarks["name"].str.lower().str.contains(pattern_ex, na=False)

,city,name,distance_from_center_m
0,Amsterdam,Joods Historisch Museum,73.1
1,Amsterdam,Mozes en Aäronkerk,87.1
2,Amsterdam,Portuguese Synagogue (Amsterdam),89.0
5,Amsterdam,Markenplein,137.8
8,Amsterdam,Stopera,170.5
10,Amsterdam,290 Square Meters,181.1
11,Amsterdam,Waterlooplein,184.2
12,Amsterdam,Reinwardt Academie,185.9
13,Amsterdam,Jodenbreestraat,188.1
14,Amsterdam,Maupoleum,202.8
15,Amsterdam,Jodenbuurt,205.3
16,Amsterdam,ASCII (squat),228.5
17,Amsterdam,Houtkopersburgwal,249.2
18,Amsterdam,Blauwbrug,261.0
19,Amsterdam,Euronext Amsterdam,261.8
504,Barcelona,Plaça de Catalunya,142.4
505,Barcelona,"Ronda de la Universitat, Barcelona",161.8
509,Barcelona,Coliseum (Barcelona),220.1
510,Barcelona,Gran Via de les Corts Catalanes,267.0
511,Barcelona,Font de Canaletes,268.6
512,Barcelona,Santa Anna de Barcelona,287.0
513,Barcelona,Portal de l'Àngel,290.7
515,Barcelona,Col·legi Casp,336.1
516,Barcelona,Conservatori Superior de Música del Liceu,395.3
518,Barcelona,"Plaça de la Universitat, Barcelona",427.0
519,Barcelona,Statistical Institute of Catalonia,430.2
521,Barcelona,Els Quatre Gats,445.0
522,Barcelona,Centre de Cultura Contemporània de Barcelona,451.1
523,Barcelona,Casa Martí,451.2
524,Barcelona,Museum of Modernism Barcelona,452.4
1001,Berlin,Marmorhaus,0.0
1003,Berlin,Old Synagogue (Berlin),123.1
1004,Berlin,"St. Mary's Church, Berlin",128.6
1006,Berlin,Neptune Fountain (Berlin),134.1
1007,Berlin,AquaDom,153.5
1009,Berlin,Berlin Dungeon,187.5
1010,Berlin,Marx-Engels Forum,193.7
1013,Berlin,DDR Museum,216.8
1014,Berlin,Rotes Rathaus (Berlin U-Bahn),240.9
1015,Berlin,Liebknecht Bridge,245.2
1016,Berlin,1760 raid on Berlin,261.2
1017,Berlin,Rathauspassagen,270.6
1018,Berlin,Red Town Hall,273.3
1019,Berlin,Berlin Cathedral,279.0
1020,Berlin,Fernsehturm Berlin,314.7
1500,Columbus,Ohio Statehouse,22.3
1501,Columbus,Capitol Square,32.5
1502,Columbus,Ohio General Assembly,45.3
1503,Columbus,The Spirit of '98,63.7
1504,Columbus,Ohio Veterans Plaza,64.7
1505,Columbus,The Doughboy (Ivone),78.1
1506,Columbus,Statue of Christopher Columbus (Ohio Statehouse),79.9
1507,Columbus,Ohio Holocaust and Liberators Memorial,95.2
1508,Columbus,These Are My Jewels,103.5
1509,Columbus,Peace (Saville),107.5
1510,Columbus,William McKinley Monument,115.1
1511,Columbus,Naiads (Greaves),121.6
1512,Columbus,Hartman Building and Theater,130.4
1513,Columbus,Columbus City Hall (1872–1921),131.2
1514,Columbus,Columbus Dispatch Building,136.1

In [ ]:
clean_lm.to_sql("raw_landmarks", engine, if_exists="replace", index=False)
with engine.connect() as conn:
    print(conn.execute(text("SELECT city, COUNT(*) FROM raw_landmarks GROUP BY city")).fetchall())

In [5]:
clean_lm.to_sql("raw_landmarks", engine, if_exists="replace", index=False)
with engine.connect() as conn:
    print(conn.execute(text("SELECT city, COUNT(*) FROM raw_landmarks GROUP BY city")).fetchall())

[('Amsterdam', 421), ('Barcelona', 380), ('Berlin', 428), ('Columbus', 411)]